spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///lending
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  idempotency:
    ttl-hours: 24
  currency: KES
